/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Insulted service. Represents a row in the &quot;SAMPLE_Insulted&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.InsultedModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.InsultedImpl}.
 * </p>
 *
 * @author nickgaskill
 * @see Insulted
 * @see com.liferay.sample.model.impl.InsultedImpl
 * @see com.liferay.sample.model.impl.InsultedModelImpl
 * @generated
 */
public interface InsultedModel extends BaseModel<Insulted> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a insulted model instance should use the {@link Insulted} interface instead.
	 */

	/**
	 * Returns the primary key of this insulted.
	 *
	 * @return the primary key of this insulted
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this insulted.
	 *
	 * @param primaryKey the primary key of this insulted
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the insulted ID of this insulted.
	 *
	 * @return the insulted ID of this insulted
	 */
	public long getInsultedId();

	/**
	 * Sets the insulted ID of this insulted.
	 *
	 * @param insultedId the insulted ID of this insulted
	 */
	public void setInsultedId(long insultedId);

	/**
	 * Returns the insult of this insulted.
	 *
	 * @return the insult of this insulted
	 */
	@AutoEscape
	public String getInsult();

	/**
	 * Sets the insult of this insulted.
	 *
	 * @param insult the insult of this insulted
	 */
	public void setInsult(String insult);

	/**
	 * Returns the group ID of this insulted.
	 *
	 * @return the group ID of this insulted
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this insulted.
	 *
	 * @param groupId the group ID of this insulted
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this insulted.
	 *
	 * @return the company ID of this insulted
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this insulted.
	 *
	 * @param companyId the company ID of this insulted
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this insulted.
	 *
	 * @return the user ID of this insulted
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this insulted.
	 *
	 * @param userId the user ID of this insulted
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this insulted.
	 *
	 * @return the user uuid of this insulted
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this insulted.
	 *
	 * @param userUuid the user uuid of this insulted
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Insulted insulted);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Insulted> toCacheModel();

	@Override
	public Insulted toEscapedModel();

	@Override
	public Insulted toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}