/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.guestbook.model.impl;

import com.liferay.docs.guestbook.model.GuestbookEntry;
import com.liferay.docs.guestbook.model.GuestbookEntryModel;
import com.liferay.docs.guestbook.model.GuestbookEntrySoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the GuestbookEntry service. Represents a row in the &quot;GB_GuestbookEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>GuestbookEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GuestbookEntryImpl}.
 * </p>
 *
 * @author Liferay
 * @see GuestbookEntryImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class GuestbookEntryModelImpl
	extends BaseModelImpl<GuestbookEntry> implements GuestbookEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a guestbook entry model instance should use the <code>GuestbookEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "GB_GuestbookEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"entryId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"email", Types.VARCHAR},
		{"message", Types.VARCHAR}, {"guestbookId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("message", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("guestbookId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GB_GuestbookEntry (uuid_ VARCHAR(75) null,entryId LONG not null primary key,name VARCHAR(75) null,email VARCHAR(75) null,message VARCHAR(75) null,guestbookId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table GB_GuestbookEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY guestbookEntry.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GB_GuestbookEntry.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long GUESTBOOKID_COLUMN_BITMASK = 4L;

	public static final long STATUS_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static GuestbookEntry toModel(GuestbookEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GuestbookEntry model = new GuestbookEntryImpl();

		model.setUuid(soapModel.getUuid());
		model.setEntryId(soapModel.getEntryId());
		model.setName(soapModel.getName());
		model.setEmail(soapModel.getEmail());
		model.setMessage(soapModel.getMessage());
		model.setGuestbookId(soapModel.getGuestbookId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<GuestbookEntry> toModels(
		GuestbookEntrySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<GuestbookEntry> models = new ArrayList<GuestbookEntry>(
			soapModels.length);

		for (GuestbookEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public GuestbookEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _entryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GuestbookEntry.class;
	}

	@Override
	public String getModelClassName() {
		return GuestbookEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GuestbookEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GuestbookEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GuestbookEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GuestbookEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GuestbookEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GuestbookEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GuestbookEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GuestbookEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GuestbookEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GuestbookEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GuestbookEntry.class.getClassLoader(), GuestbookEntry.class,
			ModelWrapper.class);

		try {
			Constructor<GuestbookEntry> constructor =
				(Constructor<GuestbookEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<GuestbookEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GuestbookEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GuestbookEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<GuestbookEntry, Object>>();
		Map<String, BiConsumer<GuestbookEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<GuestbookEntry, ?>>();

		attributeGetterFunctions.put("uuid", GuestbookEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<GuestbookEntry, String>)GuestbookEntry::setUuid);
		attributeGetterFunctions.put("entryId", GuestbookEntry::getEntryId);
		attributeSetterBiConsumers.put(
			"entryId",
			(BiConsumer<GuestbookEntry, Long>)GuestbookEntry::setEntryId);
		attributeGetterFunctions.put("name", GuestbookEntry::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<GuestbookEntry, String>)GuestbookEntry::setName);
		attributeGetterFunctions.put("email", GuestbookEntry::getEmail);
		attributeSetterBiConsumers.put(
			"email",
			(BiConsumer<GuestbookEntry, String>)GuestbookEntry::setEmail);
		attributeGetterFunctions.put("message", GuestbookEntry::getMessage);
		attributeSetterBiConsumers.put(
			"message",
			(BiConsumer<GuestbookEntry, String>)GuestbookEntry::setMessage);
		attributeGetterFunctions.put(
			"guestbookId", GuestbookEntry::getGuestbookId);
		attributeSetterBiConsumers.put(
			"guestbookId",
			(BiConsumer<GuestbookEntry, Long>)GuestbookEntry::setGuestbookId);
		attributeGetterFunctions.put("groupId", GuestbookEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<GuestbookEntry, Long>)GuestbookEntry::setGroupId);
		attributeGetterFunctions.put("companyId", GuestbookEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<GuestbookEntry, Long>)GuestbookEntry::setCompanyId);
		attributeGetterFunctions.put("userId", GuestbookEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<GuestbookEntry, Long>)GuestbookEntry::setUserId);
		attributeGetterFunctions.put("userName", GuestbookEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<GuestbookEntry, String>)GuestbookEntry::setUserName);
		attributeGetterFunctions.put(
			"createDate", GuestbookEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<GuestbookEntry, Date>)GuestbookEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", GuestbookEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<GuestbookEntry, Date>)GuestbookEntry::setModifiedDate);
		attributeGetterFunctions.put("status", GuestbookEntry::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<GuestbookEntry, Integer>)GuestbookEntry::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", GuestbookEntry::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<GuestbookEntry, Long>)
				GuestbookEntry::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", GuestbookEntry::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<GuestbookEntry, String>)
				GuestbookEntry::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", GuestbookEntry::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<GuestbookEntry, Date>)GuestbookEntry::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getEntryId() {
		return _entryId;
	}

	@Override
	public void setEntryId(long entryId) {
		_entryId = entryId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public String getMessage() {
		if (_message == null) {
			return "";
		}
		else {
			return _message;
		}
	}

	@Override
	public void setMessage(String message) {
		_message = message;
	}

	@JSON
	@Override
	public long getGuestbookId() {
		return _guestbookId;
	}

	@Override
	public void setGuestbookId(long guestbookId) {
		_columnBitmask |= GUESTBOOKID_COLUMN_BITMASK;

		if (!_setOriginalGuestbookId) {
			_setOriginalGuestbookId = true;

			_originalGuestbookId = _guestbookId;
		}

		_guestbookId = guestbookId;
	}

	public long getOriginalGuestbookId() {
		return _originalGuestbookId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(GuestbookEntry.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), GuestbookEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GuestbookEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GuestbookEntryImpl guestbookEntryImpl = new GuestbookEntryImpl();

		guestbookEntryImpl.setUuid(getUuid());
		guestbookEntryImpl.setEntryId(getEntryId());
		guestbookEntryImpl.setName(getName());
		guestbookEntryImpl.setEmail(getEmail());
		guestbookEntryImpl.setMessage(getMessage());
		guestbookEntryImpl.setGuestbookId(getGuestbookId());
		guestbookEntryImpl.setGroupId(getGroupId());
		guestbookEntryImpl.setCompanyId(getCompanyId());
		guestbookEntryImpl.setUserId(getUserId());
		guestbookEntryImpl.setUserName(getUserName());
		guestbookEntryImpl.setCreateDate(getCreateDate());
		guestbookEntryImpl.setModifiedDate(getModifiedDate());
		guestbookEntryImpl.setStatus(getStatus());
		guestbookEntryImpl.setStatusByUserId(getStatusByUserId());
		guestbookEntryImpl.setStatusByUserName(getStatusByUserName());
		guestbookEntryImpl.setStatusDate(getStatusDate());

		guestbookEntryImpl.resetOriginalValues();

		return guestbookEntryImpl;
	}

	@Override
	public int compareTo(GuestbookEntry guestbookEntry) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), guestbookEntry.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GuestbookEntry)) {
			return false;
		}

		GuestbookEntry guestbookEntry = (GuestbookEntry)obj;

		long primaryKey = guestbookEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		GuestbookEntryModelImpl guestbookEntryModelImpl = this;

		guestbookEntryModelImpl._originalUuid = guestbookEntryModelImpl._uuid;

		guestbookEntryModelImpl._originalGuestbookId =
			guestbookEntryModelImpl._guestbookId;

		guestbookEntryModelImpl._setOriginalGuestbookId = false;

		guestbookEntryModelImpl._originalGroupId =
			guestbookEntryModelImpl._groupId;

		guestbookEntryModelImpl._setOriginalGroupId = false;

		guestbookEntryModelImpl._originalCompanyId =
			guestbookEntryModelImpl._companyId;

		guestbookEntryModelImpl._setOriginalCompanyId = false;

		guestbookEntryModelImpl._setModifiedDate = false;

		guestbookEntryModelImpl._originalStatus =
			guestbookEntryModelImpl._status;

		guestbookEntryModelImpl._setOriginalStatus = false;

		guestbookEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GuestbookEntry> toCacheModel() {
		GuestbookEntryCacheModel guestbookEntryCacheModel =
			new GuestbookEntryCacheModel();

		guestbookEntryCacheModel.uuid = getUuid();

		String uuid = guestbookEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			guestbookEntryCacheModel.uuid = null;
		}

		guestbookEntryCacheModel.entryId = getEntryId();

		guestbookEntryCacheModel.name = getName();

		String name = guestbookEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			guestbookEntryCacheModel.name = null;
		}

		guestbookEntryCacheModel.email = getEmail();

		String email = guestbookEntryCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			guestbookEntryCacheModel.email = null;
		}

		guestbookEntryCacheModel.message = getMessage();

		String message = guestbookEntryCacheModel.message;

		if ((message != null) && (message.length() == 0)) {
			guestbookEntryCacheModel.message = null;
		}

		guestbookEntryCacheModel.guestbookId = getGuestbookId();

		guestbookEntryCacheModel.groupId = getGroupId();

		guestbookEntryCacheModel.companyId = getCompanyId();

		guestbookEntryCacheModel.userId = getUserId();

		guestbookEntryCacheModel.userName = getUserName();

		String userName = guestbookEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			guestbookEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			guestbookEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			guestbookEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			guestbookEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			guestbookEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		guestbookEntryCacheModel.status = getStatus();

		guestbookEntryCacheModel.statusByUserId = getStatusByUserId();

		guestbookEntryCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = guestbookEntryCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			guestbookEntryCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			guestbookEntryCacheModel.statusDate = statusDate.getTime();
		}
		else {
			guestbookEntryCacheModel.statusDate = Long.MIN_VALUE;
		}

		return guestbookEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GuestbookEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GuestbookEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GuestbookEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((GuestbookEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GuestbookEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GuestbookEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GuestbookEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GuestbookEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, GuestbookEntry>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _entryId;
	private String _name;
	private String _email;
	private String _message;
	private long _guestbookId;
	private long _originalGuestbookId;
	private boolean _setOriginalGuestbookId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private GuestbookEntry _escapedModel;

}