/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the InsultLog service. Represents a row in the &quot;SAMPLE_InsultLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.InsultLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.InsultLogImpl}.
 * </p>
 *
 * @author nickgaskill
 * @see InsultLog
 * @see com.liferay.sample.model.impl.InsultLogImpl
 * @see com.liferay.sample.model.impl.InsultLogModelImpl
 * @generated
 */
public interface InsultLogModel extends BaseModel<InsultLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a insult log model instance should use the {@link InsultLog} interface instead.
	 */

	/**
	 * Returns the primary key of this insult log.
	 *
	 * @return the primary key of this insult log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this insult log.
	 *
	 * @param primaryKey the primary key of this insult log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the insult log ID of this insult log.
	 *
	 * @return the insult log ID of this insult log
	 */
	public long getInsultLogId();

	/**
	 * Sets the insult log ID of this insult log.
	 *
	 * @param insultLogId the insult log ID of this insult log
	 */
	public void setInsultLogId(long insultLogId);

	/**
	 * Returns the insult of this insult log.
	 *
	 * @return the insult of this insult log
	 */
	@AutoEscape
	public String getInsult();

	/**
	 * Sets the insult of this insult log.
	 *
	 * @param insult the insult of this insult log
	 */
	public void setInsult(String insult);

	/**
	 * Returns the rating of this insult log.
	 *
	 * @return the rating of this insult log
	 */
	@AutoEscape
	public String getRating();

	/**
	 * Sets the rating of this insult log.
	 *
	 * @param rating the rating of this insult log
	 */
	public void setRating(String rating);

	/**
	 * Returns the group ID of this insult log.
	 *
	 * @return the group ID of this insult log
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this insult log.
	 *
	 * @param groupId the group ID of this insult log
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this insult log.
	 *
	 * @return the company ID of this insult log
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this insult log.
	 *
	 * @param companyId the company ID of this insult log
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this insult log.
	 *
	 * @return the user ID of this insult log
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this insult log.
	 *
	 * @param userId the user ID of this insult log
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this insult log.
	 *
	 * @return the user uuid of this insult log
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this insult log.
	 *
	 * @param userUuid the user uuid of this insult log
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(InsultLog insultLog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<InsultLog> toCacheModel();

	@Override
	public InsultLog toEscapedModel();

	@Override
	public InsultLog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}