/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tour.portlet.tasks.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Setup service. Represents a row in the &quot;Task_Setup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tour.portlet.tasks.model.impl.SetupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tour.portlet.tasks.model.impl.SetupImpl}.
 * </p>
 *
 * @author nickgaskill
 * @see Setup
 * @see com.tour.portlet.tasks.model.impl.SetupImpl
 * @see com.tour.portlet.tasks.model.impl.SetupModelImpl
 * @generated
 */
public interface SetupModel extends BaseModel<Setup> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a setup model instance should use the {@link Setup} interface instead.
	 */

	/**
	 * Returns the primary key of this setup.
	 *
	 * @return the primary key of this setup
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this setup.
	 *
	 * @param primaryKey the primary key of this setup
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the setup ID of this setup.
	 *
	 * @return the setup ID of this setup
	 */
	public long getSetupId();

	/**
	 * Sets the setup ID of this setup.
	 *
	 * @param setupId the setup ID of this setup
	 */
	public void setSetupId(long setupId);

	/**
	 * Returns the name of this setup.
	 *
	 * @return the name of this setup
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this setup.
	 *
	 * @param name the name of this setup
	 */
	public void setName(String name);

	/**
	 * Returns the description of this setup.
	 *
	 * @return the description of this setup
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this setup.
	 *
	 * @param description the description of this setup
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this setup.
	 *
	 * @return the status of this setup
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this setup.
	 *
	 * @param status the status of this setup
	 */
	public void setStatus(String status);

	/**
	 * Returns the group ID of this setup.
	 *
	 * @return the group ID of this setup
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this setup.
	 *
	 * @param groupId the group ID of this setup
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this setup.
	 *
	 * @return the company ID of this setup
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this setup.
	 *
	 * @param companyId the company ID of this setup
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this setup.
	 *
	 * @return the user ID of this setup
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this setup.
	 *
	 * @param userId the user ID of this setup
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this setup.
	 *
	 * @return the user uuid of this setup
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this setup.
	 *
	 * @param userUuid the user uuid of this setup
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Setup setup);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Setup> toCacheModel();

	@Override
	public Setup toEscapedModel();

	@Override
	public Setup toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}