/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tour.portlet.tasks.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Inventory service. Represents a row in the &quot;Task_Inventory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tour.portlet.tasks.model.impl.InventoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tour.portlet.tasks.model.impl.InventoryImpl}.
 * </p>
 *
 * @author nickgaskill
 * @see Inventory
 * @see com.tour.portlet.tasks.model.impl.InventoryImpl
 * @see com.tour.portlet.tasks.model.impl.InventoryModelImpl
 * @generated
 */
public interface InventoryModel extends BaseModel<Inventory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a inventory model instance should use the {@link Inventory} interface instead.
	 */

	/**
	 * Returns the primary key of this inventory.
	 *
	 * @return the primary key of this inventory
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this inventory.
	 *
	 * @param primaryKey the primary key of this inventory
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the inventory ID of this inventory.
	 *
	 * @return the inventory ID of this inventory
	 */
	public long getInventoryId();

	/**
	 * Sets the inventory ID of this inventory.
	 *
	 * @param inventoryId the inventory ID of this inventory
	 */
	public void setInventoryId(long inventoryId);

	/**
	 * Returns the name of this inventory.
	 *
	 * @return the name of this inventory
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this inventory.
	 *
	 * @param name the name of this inventory
	 */
	public void setName(String name);

	/**
	 * Returns the description of this inventory.
	 *
	 * @return the description of this inventory
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this inventory.
	 *
	 * @param description the description of this inventory
	 */
	public void setDescription(String description);

	/**
	 * Returns the group ID of this inventory.
	 *
	 * @return the group ID of this inventory
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this inventory.
	 *
	 * @param groupId the group ID of this inventory
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this inventory.
	 *
	 * @return the company ID of this inventory
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this inventory.
	 *
	 * @param companyId the company ID of this inventory
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this inventory.
	 *
	 * @return the user ID of this inventory
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this inventory.
	 *
	 * @param userId the user ID of this inventory
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this inventory.
	 *
	 * @return the user uuid of this inventory
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this inventory.
	 *
	 * @param userUuid the user uuid of this inventory
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Inventory inventory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Inventory> toCacheModel();

	@Override
	public Inventory toEscapedModel();

	@Override
	public Inventory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}